const pt = {
  lang: "pt",
  nav: {
    home: "Início",
    services: "Serviços",
    about: "Sobre Nós",
    how: "Como Funciona",
    work: "O Nosso Trabalho",
    reviews: "Avaliações",
    faq: "Perguntas Frequentes",
    contact: "Contacto",
    quote: "Pedir Orçamento Grátis",
    menu: "Menu",
    close: "Fechar",
  },
  common: {
    phone: "+351 913 118 813",
    email: "sparkleshinelimpezas@gmail.com",
    location: "Lisboa, Portugal",
    callUs: "Ligue-nos",
    learnMore: "Saber mais",
    requestQuote: "Pedir Orçamento",
    getQuote: "Pedir Orçamento Grátis",
    send: "Enviar",
    sending: "A enviar…",
    required: "Obrigatório",
  },
  hero: {
    overline: "Serviço de Limpeza · Lisboa, Portugal",
    line1: "Espaços impecáveis.",
    line2: "Menos com que se preocupar.",
    sub: "Serviços de limpeza residencial e comercial em Lisboa, adaptados à sua forma de viver e trabalhar.",
    quote: "Pedir Orçamento Grátis",
    explore: "Ver Serviços",
    trust: ["Serviço profissional", "Soluções de limpeza à medida", "Produtos ecológicos", "Residencial e comercial"],
  },
  marquee: ["Limpeza Residencial", "Limpeza Comercial", "Limpeza Profunda", "Serviços Especializados", "Lisboa, Portugal"],
  servicesHome: {
    overline: "O que fazemos",
    title: "Limpeza à medida do seu espaço.",
    sub: "Três formas de ajudar — cada visita adaptada à sua casa ou empresa.",
    items: [
      {
        slug: "residential-cleaning",
        title: "Limpeza Residencial",
        desc: "Para casas, apartamentos e espaços de habitação. Limpeza regular ou profunda, feita com cuidado e atenção ao detalhe.",
        benefits: ["Limpeza regular e profunda", "Cozinhas, casas de banho, salas", "Produtos seguros e ecológicos"],
      },
      {
        slug: "commercial-cleaning",
        title: "Limpeza Comercial",
        desc: "Para escritórios, lojas e espaços profissionais. Um serviço consistente e pontual que mantém o seu negócio apresentável.",
        benefits: ["Horários flexíveis", "Equipa consistente e fiável", "Adaptado às suas instalações"],
      },
      {
        slug: "specialty-cleaning",
        title: "Serviços Especializados",
        desc: "Para necessidades de limpeza mais profundas ou específicas. Diga-nos o que precisa e desenhamos o serviço à sua medida.",
        benefits: ["Limpeza profunda", "Projectos pontuais", "Soluções à medida"],
      },
    ],
  },
  how: {
    overline: "Como funciona",
    title: "Simples do início ao fim.",
    steps: [
      { n: "01", title: "Diga-nos o que precisa", desc: "Ligue, envie mensagem ou preencha o formulário. Bastam alguns detalhes sobre o seu espaço." },
      { n: "02", title: "Compreendemos o seu espaço", desc: "Ouvimos as suas prioridades e criamos um plano de limpeza à medida da sua vida ou do seu negócio." },
      { n: "03", title: "Realizamos a limpeza", desc: "Os nossos profissionais, experientes e pontuais, limpam com cuidado e com produtos seguros." },
      { n: "04", title: "Desfrute da diferença", desc: "Volte a encontrar um espaço verdadeiramente limpo — calmo, fresco e bem cuidado." },
    ],
  },
  why: {
    overline: "Porquê a Sparkline & Shine",
    title: "Cuidado em cada canto.",
    pillars: [
      { title: "Atenção ao Detalhe", desc: "Concentramo-nos nos pequenos detalhes que fazem um espaço sentir-se verdadeiramente limpo." },
      { title: "Serviço Fiável", desc: "Profissionais, pontuais e consistentes. Pode contar connosco com confiança." },
      { title: "Soluções à Medida", desc: "Não há dois espaços iguais. O seu plano de limpeza é adaptado às suas necessidades." },
      { title: "Abordagem Ecológica", desc: "Utilizamos produtos de limpeza seguros e ecológicos, suaves para a sua casa e família." },
    ],
  },
  work: {
    overline: "O nosso trabalho",
    title: "A diferença, ao detalhe.",
    sub: "Arraste o cursor para comparar. As fotografias apresentadas são ilustrativas enquanto preparamos o nosso portfólio.",
    before: "Antes",
    after: "Depois",
    note: "Exemplo ilustrativo",
    galleryNote: "Fotografia ilustrativa — esta galeria está pronta para receber as fotografias dos projectos da empresa.",
    items: ["Cozinhas", "Casas de banho", "Salas", "Quartos", "Escritórios", "Lojas"],
  },
  reviews: {
    overline: "Avaliações",
    title: "O que dizem os nossos clientes.",
    sub: "Palavras reais de clientes reais. As avaliações verificadas do Google aparecerão aqui assim que forem ligadas.",
    items: [
      {
        name: "Mary Mitchell",
        meta: "Testemunho de cliente · partilhado no nosso site anterior",
        text: "Fiquei impressionada com o nível de profissionalismo e atenção ao detalhe desta empresa. Fazem verdadeiramente tudo para garantir que os clientes ficam satisfeitos com os serviços. Recomendo vivamente!",
      },
    ],
    empty: "Mais avaliações verificadas a caminho.",
  },
  cta: {
    title: "Pronto para um espaço mais limpo?",
    sub: "Fale-nos da sua casa ou empresa e preparamos um orçamento gratuito, sem compromisso.",
    quote: "Pedir Orçamento Grátis",
    call: "Ligar +351 913 118 813",
  },
  servicesPage: {
    overline: "Serviços",
    title: "Limpeza à medida do seu espaço.",
    sub: "Limpeza residencial, comercial e especializada em Lisboa — cada serviço adaptado ao cliente.",
  },
  serviceDetail: {
    includes: "O que está incluído",
    whoFor: "Para quem é",
    expect: "O que pode esperar",
    request: "Pedir Orçamento",
    other: "Explorar outros serviços",
    back: "Todos os serviços",
    residential: {
      title: "Limpeza Residencial",
      intro: "Uma casa limpa muda a forma como o dia corre. Limpamos casas e apartamentos em Lisboa com cuidado, discrição e atenção ao detalhe — no horário que lhe convier.",
      includes: [
        "Limpeza regular — visitas semanais, quinzenais ou mensais para manter a sua casa sempre fresca",
        "Limpeza profunda — uma limpeza minuciosa de alto a baixo para cozinhas, casas de banho e salas",
        "Limpeza de apartamentos e moradias — adaptada à dimensão e ao ritmo do seu agregado",
      ],
      confirm: "Serviços adicionais, como limpezas de mudança de casa (entrada e saída), podem ser combinados a pedido — confirme os detalhes com a nossa equipa.",
      whoFor: "Famílias, profissionais, senhorios e todos os que querem a sua casa bem cuidada — seja numa visita regular ou numa limpeza profunda pontual.",
      expect: "Um profissional pontual e experiente; produtos seguros e ecológicos; e uma casa que se sente verdadeiramente limpa ao regressar.",
    },
    commercial: {
      title: "Limpeza Comercial",
      headline: "O seu negócio merece um ambiente mais limpo.",
      intro: "A primeira impressão começa à porta. Mantemos escritórios, lojas e espaços profissionais em Lisboa limpos, apresentáveis e acolhedores — com fiabilidade e sem perturbações.",
      includes: [
        "Limpeza de escritórios — postos de trabalho, salas de reunião, copas e instalações sanitárias",
        "Limpeza de lojas e pequenos negócios — espaços de atendimento sempre impecáveis",
        "Horários flexíveis — antes da abertura, depois do fecho ou em articulação com a sua equipa",
      ],
      whoFor: "Escritórios, lojas, pequenos negócios, consultórios e imóveis comerciais que valorizam consistência e apresentação.",
      expect: "Uma equipa consistente e fiável; um plano de limpeza desenhado para as suas instalações e horários; e um espaço que clientes e colaboradores notam pelas razões certas.",
    },
    specialty: {
      title: "Serviços Especializados",
      headline: "Diga-nos o que precisa de limpar.",
      intro: "Alguns espaços precisam de mais do que uma visita padrão. A limpeza profunda e os trabalhos especializados são desenhados à medida das suas necessidades — conte-nos a situação e propomos a abordagem certa.",
      includes: [
        "Limpeza profunda — limpeza intensiva e detalhada de qualquer divisão ou de todo o imóvel",
        "Limpeza especializada — para superfícies, situações ou ocasiões particulares",
        "Soluções à medida — um plano construído em torno do que o seu espaço realmente precisa",
      ],
      whoFor: "Quem tem um desafio de limpeza que não cabe numa lista padrão — uma cozinha que precisa de atenção, um imóvel para refrescar, ou algo inteiramente específico.",
      expect: "Uma conversa honesta sobre o que precisa, uma proposta clara da nossa equipa e um trabalho cuidado e minucioso com produtos seguros.",
    },
  },
  about: {
    overline: "Sobre nós",
    title: "Uma paixão por espaços limpos e saudáveis.",
    p1: "A Sparkline & Shine nasceu em Lisboa de uma convicção simples: um espaço limpo muda a forma como as pessoas se sentem. O que começou como uma paixão pela limpeza e pela atenção ao detalhe cresceu e tornou-se um serviço construído sobre qualidade, confiança e cuidado genuíno.",
    p2: "Limpamos casas e locais de trabalho por toda a cidade e tratamos cada espaço como se fosse nosso. Isso significa produtos seguros e ecológicos, técnicas modernas e profissionais que se orgulham do resultado — não apenas da lista de tarefas.",
    p3: "A nossa promessa é simples: pessoas fiáveis, trabalho honesto e um espaço verdadeiramente limpo quando saímos.",
    valuesTitle: "Aquilo em que acreditamos",
    values: [
      { title: "Qualidade", desc: "Cada canto, em cada visita — sempre o mesmo padrão de cuidado." },
      { title: "Confiança", desc: "Famílias e empresas confiam-nos as suas chaves. Nunca o encaramos de ânimo leve." },
      { title: "Fiabilidade", desc: "Pontuais, consistentes e fáceis de contactar." },
      { title: "Cuidado", desc: "Produtos seguros e trabalho cuidadoso, para espaços saudáveis." },
    ],
  },
  faq: {
    overline: "Perguntas frequentes",
    title: "Perguntas, respondidas.",
    sub: "Não encontra o que procura? Ligue-nos ou envie uma mensagem — teremos todo o gosto em ajudar.",
    search: "Pesquisar perguntas…",
    noResults: "Nenhuma pergunta corresponde à sua pesquisa.",
    contactNote: "Contacte a nossa equipa para mais detalhes.",
    items: [
      { q: "Que serviços de limpeza oferecem?", a: "Oferecemos limpeza residencial, limpeza comercial e serviços especializados — incluindo limpeza regular, limpeza profunda e soluções à medida para casas e empresas em Lisboa." },
      { q: "Utilizam produtos ecológicos?", a: "Sim. Utilizamos produtos de limpeza seguros e ecológicos e técnicas modernas, para que o seu espaço fique limpo e saudável para as pessoas (e animais) que nele vivem." },
      { q: "Como peço um orçamento?", a: "Utilize o formulário Pedir Orçamento Grátis neste site, ligue +351 913 118 813 ou envie email para sparkleshinelimpezas@gmail.com. Fale-nos do seu espaço e preparamos um orçamento gratuito, sem compromisso." },
      { q: "Quanto custa uma limpeza?", a: "Cada espaço é diferente, por isso preparamos orçamentos individualmente em vez de publicar preços fixos. Peça um orçamento gratuito e a nossa equipa responderá com os detalhes." },
      { q: "Que zonas servem?", a: "Estamos sediados em Lisboa, Portugal, e servimos clientes em toda a cidade. Para zonas fora de Lisboa, contacte a nossa equipa para mais detalhes." },
      { q: "Qual é a diferença entre limpeza regular e limpeza profunda?", a: "A limpeza regular mantém o seu espaço consistentemente fresco, num horário definido. A limpeza profunda é um serviço minucioso de alto a baixo — ideal como primeira visita ou renovação periódica." },
      { q: "Preciso de estar em casa durante a limpeza?", a: "Fica inteiramente ao seu critério. Muitos clientes estão em casa; outros confiam-nos o acesso. Contacte a nossa equipa para combinar o que funcionar melhor para si." },
      { q: "Como agendo ou reagendo uma visita?", a: "Basta ligar +351 913 118 813 ou enviar email para sparkleshinelimpezas@gmail.com e combinamos a hora que lhe convier. Para condições e prazos de agendamento, contacte a nossa equipa para mais detalhes." },
      { q: "Que métodos de pagamento aceitam?", a: "Contacte a nossa equipa para mais detalhes sobre métodos de pagamento e condições." },
      { q: "Fazem limpeza de escritórios ou lojas?", a: "Sim — a limpeza comercial é um dos nossos serviços principais. Limpamos escritórios, lojas e instalações profissionais com horários flexíveis em torno do seu horário de funcionamento." },
    ],
  },
  contact: {
    overline: "Contacto",
    title: "Vamos falar sobre o seu espaço.",
    sub: "Ligue, envie email ou deixe uma mensagem — respondemos pessoalmente a cada pedido.",
    call: "Ligar",
    emailLabel: "Email",
    quoteLabel: "Orçamento",
    quoteText: "Prefere um orçamento por escrito? Utilize o nosso formulário.",
    formTitle: "Envie-nos uma mensagem",
    name: "Nome completo",
    email: "Email",
    phone: "Telefone",
    message: "Mensagem",
    messagePh: "Fale-nos do seu espaço e do que precisa…",
    send: "Enviar Mensagem",
    success: "Obrigado — a sua mensagem foi enviada. Entraremos em contacto em breve.",
    error: "Algo correu mal. Tente novamente ou ligue-nos directamente.",
    mapNote: "Sediados em Lisboa · ao serviço da cidade e bairros envolventes",
  },
  quotePage: {
    overline: "Orçamento gratuito",
    title: "Peça o seu orçamento gratuito.",
    sub: "Fale-nos do seu espaço. Demora menos de dois minutos e não tem qualquer compromisso.",
    step1: "Os seus dados",
    step2: "O seu espaço",
    step3: "A sua limpeza",
    back: "Voltar",
    next: "Continuar",
    submit: "Pedir o Meu Orçamento",
    fields: {
      name: "Nome completo",
      email: "Email",
      phone: "Telefone",
      clientType: "É para…",
      residential: "Casa",
      commercial: "Empresa",
      propertyType: "Tipo de imóvel",
      propertyTypes: ["Apartamento", "Moradia", "Escritório", "Loja", "Outro"],
      area: "Morada / zona em Lisboa",
      rooms: "Número de divisões",
      size: "Área aproximada (m²)",
      cleaningType: "Tipo de limpeza",
      cleaningTypes: ["Limpeza regular", "Limpeza profunda", "Limpeza especializada", "Ainda não sei"],
      frequency: "Frequência",
      frequencies: ["Uma vez", "Semanal", "Quinzenal", "Mensal"],
      date: "Data preferida",
      time: "Hora preferida",
      details: "Detalhes adicionais",
      detailsPh: "Algo que devamos saber — animais, prioridades, acessos…",
      photo: "Adicionar fotografia (opcional)",
      photoHint: "JPG, PNG ou WebP, até 5MB",
    },
    errors: {
      required: "Campo obrigatório",
      email: "Introduza um endereço de email válido",
      phone: "Introduza um número de telefone válido",
      fileType: "Apenas imagens JPG, PNG ou WebP",
      fileSize: "A fotografia deve ter menos de 5MB",
    },
    successTitle: "Pedido recebido.",
    successText: "Obrigado — a nossa equipa irá analisar os seus dados e responder em breve. Se for urgente, ligue +351 913 118 813.",
    errorText: "Algo correu mal ao enviar. Tente novamente ou ligue +351 913 118 813.",
  },
  chat: {
    title: "Sparkline & Shine",
    subtitle: "Como podemos ajudar?",
    open: "Fale connosco",
    placeholder: "Escreva a sua mensagem…",
    send: "Enviar",
    greeting: "Olá! Sou o assistente da Sparkline & Shine. Posso ajudar a escolher um serviço, explicar o que oferecemos ou indicar como pedir um orçamento gratuito. Em que posso ajudar?",
    quick: ["Pedir orçamento", "Qual o serviço ideal para mim?", "Limpeza residencial", "Limpeza comercial", "Falar com alguém"],
    error: "Desculpe — não consegui responder agora. Pode contactar a equipa através do +351 913 118 813.",
    leadTitle: "Falar com alguém",
    leadText: "Deixe os seus dados e a equipa Sparkline & Shine entrará em contacto.",
    leadSend: "Pedir contacto",
    leadSuccess: "Obrigado — a equipa entrará em contacto em breve.",
  },
  cookie: {
    text: "Utilizamos um pequeno número de cookies para fazer este site funcionar e perceber como é utilizado.",
    accept: "Aceitar",
    decline: "Recusar",
    policy: "Política de Cookies",
  },
  legal: {
    privacy: {
      title: "Política de Privacidade",
      intro: "Esta política explica como a Sparkline & Shine Cleaning Service trata os dados pessoais submetidos através deste site. Este texto é um modelo estruturado e deve ser revisto pela empresa antes da publicação.",
      sections: [
        { h: "O que recolhemos", p: "Quando pede um orçamento ou nos contacta, recolhemos os dados que fornece: nome, endereço de email, número de telefone e informação sobre o seu espaço." },
        { h: "Como os utilizamos", p: "Utilizamos os seus dados apenas para responder ao seu pedido, preparar orçamentos e prestar os nossos serviços de limpeza. Não vendemos dados pessoais." },
        { h: "Os seus direitos", p: "Ao abrigo do RGPD, pode pedir acesso, rectificação ou eliminação dos seus dados pessoais a qualquer momento, através do email sparkleshinelimpezas@gmail.com." },
      ],
    },
    terms: {
      title: "Termos de Serviço",
      intro: "Estes termos regulam a utilização deste site. Este texto é um modelo estruturado e deve ser revisto pela empresa antes da publicação.",
      sections: [
        { h: "O site", p: "Este site fornece informação sobre a Sparkline & Shine Cleaning Service e permite aos visitantes pedir orçamentos e fazer perguntas." },
        { h: "Orçamentos", p: "Os orçamentos pedidos através deste site são gratuitos e sem compromisso. O preço final é confirmado pela equipa antes de qualquer serviço ser agendado." },
        { h: "Contacto", p: "Para qualquer questão sobre estes termos, contacte sparkleshinelimpezas@gmail.com." },
      ],
    },
    cookies: {
      title: "Política de Cookies",
      intro: "Esta política explica como este site utiliza cookies. Este texto é um modelo estruturado e deve ser revisto pela empresa antes da publicação.",
      sections: [
        { h: "Armazenamento essencial", p: "Guardamos as suas preferências de idioma e de cookies no seu navegador para que o site se lembre das suas escolhas." },
        { h: "Análise", p: "Se ferramentas de análise forem activadas no futuro, serão descritas aqui e apenas activadas após o seu consentimento." },
      ],
    },
  },
  notFound: {
    title: "Página não encontrada",
    text: "A página que procura não existe ou foi movida.",
    back: "Voltar à página inicial",
  },
  footer: {
    tagline: "Limpeza residencial e comercial profissional em Lisboa. Espaços impecáveis, menos preocupações.",
    services: "Serviços",
    company: "Empresa",
    contactCol: "Contacto",
    residential: "Limpeza Residencial",
    commercial: "Limpeza Comercial",
    specialty: "Serviços Especializados",
    credit: "Website criado por",
    creditName: "Hub of Ecom",
    privacy: "Privacidade",
    terms: "Termos",
    cookies: "Cookies",
    rights: "Todos os direitos reservados.",
  },
  seo: {
    home: { title: "Sparkline & Shine — Serviços de Limpeza em Lisboa", desc: "Limpeza residencial e comercial fiável em Lisboa. Produtos ecológicos, soluções à medida, orçamentos gratuitos." },
    services: { title: "Serviços de Limpeza em Lisboa — Sparkline & Shine", desc: "Limpeza residencial, comercial e especializada em Lisboa. À medida do seu espaço, com produtos ecológicos." },
    residential: { title: "Limpeza de Casas e Apartamentos Lisboa — Sparkline & Shine", desc: "Limpeza residencial regular e profunda em Lisboa. Profissionais experientes, produtos ecológicos, orçamentos gratuitos." },
    commercial: { title: "Limpeza Comercial e de Escritórios Lisboa — Sparkline & Shine", desc: "Limpeza comercial fiável para escritórios, lojas e espaços profissionais em Lisboa. Horários flexíveis, orçamentos gratuitos." },
    specialty: { title: "Limpeza Profunda e Especializada Lisboa — Sparkline & Shine", desc: "Limpeza profunda e serviços especializados à medida em Lisboa. Diga-nos o que precisa — orçamentos gratuitos." },
    about: { title: "Sobre a Sparkline & Shine — Empresa de Limpeza Lisboa", desc: "Uma empresa de limpeza em Lisboa construída sobre qualidade, confiança e atenção ao detalhe, ao serviço de casas e empresas." },
    work: { title: "O Nosso Trabalho — Sparkline & Shine Lisboa", desc: "Veja a diferença que uma limpeza profissional faz. Cozinhas, casas de banho, salas e escritórios em Lisboa." },
    faq: { title: "Perguntas Frequentes — Sparkline & Shine Lisboa", desc: "Respostas sobre os nossos serviços de limpeza, produtos ecológicos, orçamentos, agendamento e zonas de serviço em Lisboa." },
    contact: { title: "Contacto — Sparkline & Shine Limpezas Lisboa", desc: "Ligue +351 913 118 813 ou envie email à Sparkline & Shine para serviços de limpeza em Lisboa. Orçamentos gratuitos." },
    quote: { title: "Pedir Orçamento Grátis — Sparkline & Shine Lisboa", desc: "Peça um orçamento de limpeza gratuito e sem compromisso em Lisboa. Limpeza residencial, comercial e especializada." },
  },
};

export default pt;
