const en = {
  lang: "en",
  nav: {
    home: "Home",
    services: "Services",
    about: "About",
    how: "How It Works",
    work: "Our Work",
    reviews: "Reviews",
    faq: "FAQ",
    contact: "Contact",
    quote: "Get a Free Quote",
    menu: "Menu",
    close: "Close",
  },
  common: {
    phone: "+351 913 118 813",
    email: "sparkleshinelimpezas@gmail.com",
    location: "Lisbon, Portugal",
    callUs: "Call us",
    learnMore: "Learn more",
    requestQuote: "Request a Quote",
    getQuote: "Get a Free Quote",
    send: "Send",
    sending: "Sending…",
    required: "Required",
  },
  hero: {
    overline: "Cleaning Service · Lisbon, Portugal",
    line1: "Spotless spaces.",
    line2: "Less to worry about.",
    sub: "Reliable residential and commercial cleaning services in Lisbon, tailored to the way you live and work.",
    quote: "Get a Free Quote",
    explore: "Explore Services",
    trust: ["Professional service", "Tailored cleaning solutions", "Eco-conscious products", "Residential & commercial"],
  },
  marquee: ["Residential Cleaning", "Commercial Cleaning", "Deep Cleaning", "Specialty Services", "Lisbon, Portugal"],
  servicesHome: {
    overline: "What we do",
    title: "Cleaning that fits your space.",
    sub: "Three ways we can help — every visit adapted to your home or business.",
    items: [
      {
        slug: "residential-cleaning",
        title: "Residential Cleaning",
        desc: "For homes, apartments and living spaces. Regular or deep cleaning, carried out with care and attention to detail.",
        benefits: ["Regular & deep cleaning", "Kitchens, bathrooms, living areas", "Safe, eco-conscious products"],
      },
      {
        slug: "commercial-cleaning",
        title: "Commercial Cleaning",
        desc: "For offices, shops and professional spaces. Consistent, punctual service that keeps your business presentable.",
        benefits: ["Flexible scheduling", "Consistent, reliable team", "Tailored to your premises"],
      },
      {
        slug: "specialty-cleaning",
        title: "Specialty Services",
        desc: "For deeper or specific cleaning requirements. Tell us what needs attention and we will shape the service around it.",
        benefits: ["Deep cleaning", "One-off projects", "Tailored solutions"],
      },
    ],
  },
  how: {
    overline: "How it works",
    title: "Simple from start to finish.",
    steps: [
      { n: "01", title: "Tell us what you need", desc: "Call, message or send the quote form. A few details about your space is all it takes." },
      { n: "02", title: "We understand your space", desc: "We listen to your priorities and shape a cleaning plan around the way you live or work." },
      { n: "03", title: "We provide your cleaning service", desc: "Our trained, reliable professionals arrive on time and clean with care, using safe products." },
      { n: "04", title: "You enjoy the difference", desc: "Come back to a space that feels genuinely clean — calm, fresh and looked after." },
    ],
  },
  why: {
    overline: "Why Sparkline & Shine",
    title: "Care in every corner.",
    pillars: [
      { title: "Attention to Detail", desc: "We focus on the small things that make a space feel truly clean — not just tidy." },
      { title: "Reliable Service", desc: "Professional, punctual and consistent. You can plan around us with confidence." },
      { title: "Tailored Solutions", desc: "No two spaces are the same. Your cleaning plan is adapted to your needs." },
      { title: "Eco-Conscious Approach", desc: "We use safe, eco-friendly cleaning products that are kind to your home and family." },
    ],
  },
  work: {
    overline: "Our work",
    title: "The difference, in detail.",
    sub: "Drag the handle to compare. Photography shown is illustrative while we prepare our own project portfolio.",
    before: "Before",
    after: "After",
    note: "Illustrative example",
    galleryNote: "Illustrative photography — this gallery is ready for the company's own project photos.",
    items: ["Kitchens", "Bathrooms", "Living spaces", "Bedrooms", "Offices", "Retail spaces"],
  },
  reviews: {
    overline: "Reviews",
    title: "What our clients say.",
    sub: "Real words from real clients. Verified Google reviews will appear here as they are connected.",
    items: [
      {
        name: "Mary Mitchell",
        meta: "Client testimonial · shared via our previous website",
        text: "I was blown away by the level of professionalism and attention to detail that this company provided. They truly go above and beyond to ensure their customers are happy and satisfied with their services. Highly recommend!",
      },
    ],
    empty: "More verified reviews are on the way.",
  },
  cta: {
    title: "Ready for a cleaner space?",
    sub: "Tell us about your home or business and we'll prepare a free, no-obligation quote.",
    quote: "Get a Free Quote",
    call: "Call +351 913 118 813",
  },
  servicesPage: {
    overline: "Services",
    title: "Cleaning that fits your space.",
    sub: "Residential, commercial and specialty cleaning across Lisbon — every service tailored to the client.",
  },
  serviceDetail: {
    includes: "What's included",
    whoFor: "Who it's for",
    expect: "What to expect",
    request: "Request a Quote",
    other: "Explore other services",
    back: "All services",
    residential: {
      title: "Residential Cleaning",
      intro: "A clean home changes how a day feels. We clean houses and apartments across Lisbon with care, discretion and attention to detail — on a schedule that suits you.",
      includes: [
        "Regular cleaning — weekly, fortnightly or monthly visits to keep your home consistently fresh",
        "Deep cleaning — a thorough top-to-bottom clean for kitchens, bathrooms and living spaces",
        "Apartment & home cleaning — adapted to the size and rhythm of your household",
      ],
      confirm: "Additional services such as move-in and move-out cleaning can be arranged on request — please confirm details with our team.",
      whoFor: "Families, professionals, landlords and anyone who wants their home looked after properly — whether you need a regular visit or a one-off deep clean.",
      expect: "A punctual, trained professional; safe, eco-conscious products; and a home that feels genuinely clean when you walk back in.",
    },
    commercial: {
      title: "Commercial Cleaning",
      headline: "Your business deserves a cleaner environment.",
      intro: "First impressions are made at the door. We keep offices, shops and professional spaces in Lisbon clean, presentable and welcoming — reliably and without disruption.",
      includes: [
        "Office cleaning — workstations, meeting rooms, kitchens and washrooms",
        "Retail & small business cleaning — customer-facing spaces kept immaculate",
        "Flexible scheduling — before opening, after closing, or around your team",
      ],
      whoFor: "Offices, retail spaces, small businesses, professional practices and commercial properties that value consistency and presentation.",
      expect: "A consistent, reliable team; a cleaning plan built around your premises and hours; and a space your staff and clients notice for the right reasons.",
    },
    specialty: {
      title: "Specialty Services",
      headline: "Tell us what needs cleaning.",
      intro: "Some spaces need more than a standard visit. Deep cleaning and specialised work are shaped around your exact requirements — tell us the situation and we'll propose the right approach.",
      includes: [
        "Deep cleaning — intensive, detailed cleaning for any room or whole property",
        "Specialised cleaning — for particular surfaces, situations or occasions",
        "Tailored solutions — a plan built around what your space actually needs",
      ],
      whoFor: "Anyone with a cleaning challenge that doesn't fit a standard checklist — a neglected kitchen, a property refresh, or something entirely specific.",
      expect: "An honest conversation about what you need, a clear proposal from our team, and careful, thorough work using safe products.",
    },
  },
  about: {
    overline: "About us",
    title: "A passion for clean, healthy spaces.",
    p1: "Sparkline & Shine was founded in Lisbon on a simple belief: a clean space changes how people feel. What began as a passion for cleanliness and attention to detail has grown into a cleaning service built on quality, trust and genuine care.",
    p2: "We clean homes and workplaces across the city, and we treat every space as if it were our own. That means safe, eco-friendly products, modern techniques, and professionals who take pride in the finish — not just the checklist.",
    p3: "Our promise is straightforward: reliable people, honest work, and a space that feels truly clean when we leave.",
    valuesTitle: "What we stand for",
    values: [
      { title: "Quality", desc: "Every corner, every visit — the same careful standard." },
      { title: "Trust", desc: "Homes and businesses hand us their keys. We never take that lightly." },
      { title: "Reliability", desc: "Punctual, consistent and easy to reach." },
      { title: "Care", desc: "Safe products and thoughtful work, for healthy spaces." },
    ],
  },
  faq: {
    overline: "FAQ",
    title: "Questions, answered.",
    sub: "Can't find what you're looking for? Call us or send a message — we're happy to help.",
    search: "Search questions…",
    noResults: "No questions match your search.",
    contactNote: "Please contact our team for details.",
    items: [
      { q: "Which cleaning services do you offer?", a: "We offer residential cleaning, commercial cleaning and specialty services — including regular cleaning, deep cleaning and tailored cleaning solutions for homes and businesses in Lisbon." },
      { q: "Do you use eco-friendly products?", a: "Yes. We use safe, eco-friendly cleaning products and modern techniques, so your space is clean and healthy for the people (and pets) in it." },
      { q: "How do I get a quote?", a: "Use the Get a Free Quote form on this website, call +351 913 118 813, or email sparkleshinelimpezas@gmail.com. Tell us about your space and we'll prepare a free, no-obligation quote." },
      { q: "How much does a cleaning cost?", a: "Every space is different, so we prepare quotes individually rather than publishing fixed prices. Request a free quote and our team will respond with details." },
      { q: "Which areas do you serve?", a: "We are based in Lisbon, Portugal, and serve clients across the city. For locations outside Lisbon, please contact our team for details." },
      { q: "What's the difference between regular and deep cleaning?", a: "Regular cleaning keeps your space consistently fresh on a schedule. Deep cleaning is a thorough, top-to-bottom service for kitchens, bathrooms and every corner in between — ideal as a first visit or a periodic refresh." },
      { q: "Do I need to be home during the cleaning?", a: "That is entirely up to you. Many clients are home; others trust us with access. Please contact our team to discuss what works best for you." },
      { q: "How do I schedule or reschedule a visit?", a: "Simply call +351 913 118 813 or email sparkleshinelimpezas@gmail.com and we will arrange a time that suits you. For scheduling terms and notice periods, please contact our team for details." },
      { q: "What payment methods do you accept?", a: "Please contact our team for details about payment methods and terms." },
      { q: "Can you clean my office or shop?", a: "Yes — commercial cleaning is one of our core services. We clean offices, retail spaces and professional premises with flexible scheduling around your business hours." },
    ],
  },
  contact: {
    overline: "Contact",
    title: "Let's talk about your space.",
    sub: "Call, email or send us a message — we reply personally to every enquiry.",
    call: "Call",
    emailLabel: "Email",
    quoteLabel: "Quote",
    quoteText: "Prefer a written estimate? Use our quote form.",
    formTitle: "Send us a message",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    messagePh: "Tell us about your space and what you need…",
    send: "Send Message",
    success: "Thank you — your message has been sent. We'll be in touch soon.",
    error: "Something went wrong. Please try again or call us directly.",
    mapNote: "Based in Lisbon · serving the city and surrounding neighbourhoods",
  },
  quotePage: {
    overline: "Free quote",
    title: "Request your free quote.",
    sub: "Tell us about your space. It takes less than two minutes, and there's no obligation.",
    step1: "Your details",
    step2: "Your space",
    step3: "Your cleaning",
    back: "Back",
    next: "Continue",
    submit: "Request My Quote",
    fields: {
      name: "Full name",
      email: "Email",
      phone: "Phone",
      clientType: "This is for a…",
      residential: "Home",
      commercial: "Business",
      propertyType: "Property type",
      propertyTypes: ["Apartment", "House", "Office", "Retail space", "Other"],
      area: "Address / area in Lisbon",
      rooms: "Number of rooms",
      size: "Approximate size (m²)",
      cleaningType: "Cleaning type",
      cleaningTypes: ["Regular cleaning", "Deep cleaning", "Specialty cleaning", "Not sure yet"],
      frequency: "Frequency",
      frequencies: ["One-off", "Weekly", "Fortnightly", "Monthly"],
      date: "Preferred date",
      time: "Preferred time",
      details: "Additional details",
      detailsPh: "Anything we should know — pets, priorities, access…",
      photo: "Add a photo (optional)",
      photoHint: "JPG, PNG or WebP, up to 5MB",
    },
    errors: {
      required: "This field is required",
      email: "Please enter a valid email address",
      phone: "Please enter a valid phone number",
      fileType: "Only JPG, PNG or WebP images",
      fileSize: "Photo must be smaller than 5MB",
    },
    successTitle: "Request received.",
    successText: "Thank you — our team will review your details and get back to you shortly. If it's urgent, call us on +351 913 118 813.",
    errorText: "Something went wrong while sending. Please try again, or call +351 913 118 813.",
  },
  chat: {
    title: "Sparkline & Shine",
    subtitle: "How can we help?",
    open: "Chat with us",
    placeholder: "Type your message…",
    send: "Send",
    greeting: "Hello! I'm the Sparkline & Shine assistant. I can help you choose a service, explain what we offer, or point you to a free quote. What can I do for you?",
    quick: ["Get a quote", "Which service do I need?", "Residential cleaning", "Commercial cleaning", "Talk to someone"],
    error: "Sorry — I couldn't respond just now. You can reach the team at +351 913 118 813.",
    leadTitle: "Talk to someone",
    leadText: "Leave your details and the Sparkline & Shine team will contact you.",
    leadSend: "Request a call back",
    leadSuccess: "Thank you — the team will be in touch soon.",
  },
  cookie: {
    text: "We use a small number of cookies to make this website work and to understand how it's used.",
    accept: "Accept",
    decline: "Decline",
    policy: "Cookie Policy",
  },
  legal: {
    privacy: {
      title: "Privacy Policy",
      intro: "This policy explains how Sparkline & Shine Cleaning Service handles personal data submitted through this website. This text is a structured placeholder and should be reviewed by the business before publication.",
      sections: [
        { h: "What we collect", p: "When you request a quote or contact us, we collect the details you provide: your name, email address, phone number and information about your space." },
        { h: "How we use it", p: "We use your details only to respond to your enquiry, prepare quotes and provide our cleaning services. We do not sell personal data." },
        { h: "Your rights", p: "Under the GDPR you may request access, correction or deletion of your personal data at any time by emailing sparkleshinelimpezas@gmail.com." },
      ],
    },
    terms: {
      title: "Terms of Service",
      intro: "These terms govern the use of this website. This text is a structured placeholder and should be reviewed by the business before publication.",
      sections: [
        { h: "The website", p: "This website provides information about Sparkline & Shine Cleaning Service and allows visitors to request quotes and make enquiries." },
        { h: "Quotes", p: "Quotes requested through this website are free and without obligation. Final pricing is confirmed by the team before any service is scheduled." },
        { h: "Contact", p: "For any question about these terms, contact sparkleshinelimpezas@gmail.com." },
      ],
    },
    cookies: {
      title: "Cookie Policy",
      intro: "This policy explains how this website uses cookies. This text is a structured placeholder and should be reviewed by the business before publication.",
      sections: [
        { h: "Essential storage", p: "We store your language and cookie preferences in your browser so the website remembers your choices." },
        { h: "Analytics", p: "If analytics are enabled in future, they will be described here and only activated after your consent." },
      ],
    },
  },
  notFound: {
    title: "Page not found",
    text: "The page you're looking for doesn't exist or has moved.",
    back: "Back to homepage",
  },
  footer: {
    tagline: "Professional residential and commercial cleaning in Lisbon. Spotless spaces, less to worry about.",
    services: "Services",
    company: "Company",
    contactCol: "Contact",
    residential: "Residential Cleaning",
    commercial: "Commercial Cleaning",
    specialty: "Specialty Services",
    credit: "Website crafted by",
    creditName: "Hub of Ecom",
    privacy: "Privacy",
    terms: "Terms",
    cookies: "Cookies",
    rights: "All rights reserved.",
  },
  seo: {
    home: { title: "Sparkline & Shine — Cleaning Services in Lisbon", desc: "Reliable residential and commercial cleaning services in Lisbon. Eco-conscious products, tailored solutions, free quotes." },
    services: { title: "Cleaning Services in Lisbon — Sparkline & Shine", desc: "Residential, commercial and specialty cleaning services across Lisbon. Tailored to your space, with eco-conscious products." },
    residential: { title: "House & Apartment Cleaning Lisbon — Sparkline & Shine", desc: "Regular and deep residential cleaning in Lisbon. Trained professionals, eco-friendly products, free quotes." },
    commercial: { title: "Commercial & Office Cleaning Lisbon — Sparkline & Shine", desc: "Reliable commercial cleaning for offices, shops and professional spaces in Lisbon. Flexible scheduling, free quotes." },
    specialty: { title: "Deep & Specialty Cleaning Lisbon — Sparkline & Shine", desc: "Deep cleaning and tailored specialty cleaning services in Lisbon. Tell us what needs cleaning — free quotes." },
    about: { title: "About Sparkline & Shine — Cleaning Company Lisbon", desc: "A Lisbon cleaning company built on quality, trust and attention to detail, serving homes and businesses." },
    work: { title: "Our Work — Sparkline & Shine Lisbon", desc: "See the difference professional cleaning makes. Kitchens, bathrooms, living spaces and offices in Lisbon." },
    faq: { title: "FAQ — Sparkline & Shine Cleaning Lisbon", desc: "Answers about our cleaning services, eco-friendly products, quotes, scheduling and service areas in Lisbon." },
    contact: { title: "Contact — Sparkline & Shine Cleaning Lisbon", desc: "Call +351 913 118 813 or email Sparkline & Shine for cleaning services in Lisbon. Free quotes." },
    quote: { title: "Get a Free Quote — Sparkline & Shine Lisbon", desc: "Request a free, no-obligation cleaning quote in Lisbon. Residential, commercial and specialty cleaning." },
  },
};

export default en;
